name: "Supabase Backup and Commit"
description: "Backs up files from Supabase storage, zips them, and commits as artifact with provided name"
inputs:
  SUPABASE_URL:
    description: "Supabase Project URL"
    required: true
  SUPABASE_SERVICE_ROLE:
    description: "Supabase Service Role Key"
    required: true
  ARTIFACT_NAME:
    description: "Name of artifact to be uploaded"
    required: false
    default: "supabase-storage-backup"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run backup and zip
      run: python ${{ github.action_path }}/src/backup_script.py
      shell: bash
      env:
        SUPABASE_URL: ${{ inputs.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE: ${{ inputs.SUPABASE_SERVICE_ROLE }}
    - name: Upload Backup Zip as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        path: backup.zip
