name: "Supabase Backup"
description: "Backs up files from Supabase storage, zips them, and stores path to zip in GITHUB_ENV"
inputs:
  SUPABASE_URL:
    description: "Supabase Project URL"
    required: true
  SUPABASE_SERVICE_ROLE:
    description: "Supabase Service Role Key"
    required: true
  OUTPUT_ZIP_FILE_NAME:
    description: "Name of output zip file"
    required: false
    default: "supabase-storage-backup.zip"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run backup and zip
      run: python ${{ github.action_path }}/src/backup_script.py
      shell: bash
      env:
        SUPABASE_URL: ${{ inputs.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE: ${{ inputs.SUPABASE_SERVICE_ROLE }}
        OUTPUT_ZIP_FILE_NAME: ${{ inputs.OUTPUT_ZIP_FILE_NAME }}
